### ISSUE TITLE
Casual Stats lead to incorrect data

### ISSUE THREAD

**Issue by KieranRobson** [hmes98318/r6s-stats-api#1]
```js
{
  url: 'https://r6.tracker.network/profile/pc/MP7/',
  name: 'MP7',
  header: 'https://ubisoft-avatars.akamaized.net/f037a5a4-4f59-49d2-9d98-18e11d213c61/default_256_256.png',
  kd: 'Y7S2: Vector Glare',
  kills: '2,465',
  deaths: '1,846',
  win_: '80.15',
  wins: '416',
  losses: '102',
  time_played: 'Y7S2: Vector Glare',
  matches: 'Y7S2: Vector Glare',
  kills_match: 'Y7S2: Vector Glare',
  kills_min: 'Y7S2: Vector Glare',
  mmr: '1,336',
  rank: 'COPPER III',
  rank_img: 'https://imgur.com/w4Zdkc4.png'
}
```

Some casual stats lead to incorrect data such as `time_played` and `matches`

**Comment by hmes98318** [comment]
give me some time to resolve it.

**Comment by KieranRobson** [comment]
> give me some time to resolve it.

No worries, just thought id let you know!

**Comment by KieranRobson** [comment]
> @KieranRobson , I published a new version **`v1.1.0`** , you can try it again.

Will give it ago and let you know! Ill keep an eye out for any other bugs I find!

**Comment by KieranRobson** [comment]
@hmes98318 This has fixed the issue, Im experiencing a different bug now where I get undefined on my deployment server in docker but when I try it in docker on my pc it works

Local machine is Windows and VPS is linux so it probably has something to do with that

**Comment by hmes98318** [comment]
> @hmes98318 This has fixed the issue, Im experiencing a different bug now where I get undefined on my deployment server in docker but when I try it in docker on my pc it works
> 
> Local machine is Windows and VPS is linux so it probably has something to do with that


i try to deploy on centos 7 it works fine.
Is there any output data for me to reference?

**Comment by KieranRobson** [comment]
It doesnt output anything, even with `console.log(stats)`, Its probably my own vps just being awkward as it often is with docker and dicord bots 😆, ill look more into it and get back to you if I ever solve it 

Thanks for the update to the API!

**Comment by CrimsonTome** [comment]
>i try to deploy on CentOS 7 it works fine.
>Is there any output data for me to reference?

Is this bare metal or a CentOS  VM?

**Comment by CrimsonTome** [comment]
Specifically having issues with Ubuntu 22.04. Docker version does not matter. It's either an Ubuntu issue or something with it being ran inside a virtual machine

**Comment by CrimsonTome** [comment]
looks like it's vm issue. ran in bare node and it still doesnt work.

**Comment by hmes98318** [comment]
> Is this bare metal or a CentOS VM?

Bare metal.
I had never tested it on the Docker.

**Comment by hmes98318** [comment]
> looks like it's vm issue. ran in bare node and it still doesnt work.

this api depend on the **curl** to normal work.
maybe the docker image problem is does not have installed curl cause cannot fetch the statistics.
Try to install it might solve the problem.

**Comment by hmes98318** [comment]
I builded an image using [`node:16.17.1-slim`](https://hub.docker.com/_/node).
maybe can help with something.
[`hmes98318/r6s-stats-api`](https://hub.docker.com/repository/docker/hmes98318/r6s-stats-api)

**Comment by CrimsonTome** [comment]
this is **not** a Docker issue, this is most likely an issue with it being ran in a VM,

**Comment by hmes98318** [comment]
well, I can't help with the VM issue.

**Comment by hmes98318** [comment]
@KieranRobson, 
Will try the new version(**1.2.0**) solve this problem?
