### ISSUE TITLE
Confused

### ISSUE THREAD

**Issue by AidanTheJsDev** [hmes98318/r6s-stats-api#7]
Im a bit confused on how you get a specific thing like I just want my rank to show but when I try to add it to

```js
let ranked = await R6.rank(platform, name, rank)
console.log('Ranked', ranked)
```

I just get an error that says

```txt
let ranked = await R6.rank(platform, name, rank)
                                             ^

ReferenceError: rank is not defined
```

Also please update this for the new Ranked 2.0

**Comment by hmes98318** [comment]
Your request format is wrong.
The followinig is correct format.
```js
async function main() {
    let rank = await R6.rank(platform, name);
    console.log('rank', rank);
}
main();
```
[example link](https://github.com/hmes98318/r6s-stats-api#rankplatform-string-name-string)

**Comment by AidanTheJsDev** [comment]
> Your request format is wrong. The followinig is correct format.
> 
> ```js
> async function main() {
>     let rank = await R6.rank(platform, name);
>     console.log('rank', rank);
> }
> main();
> ```
> 
> [example link](https://github.com/hmes98318/r6s-stats-api#rankplatform-string-name-string)

Im just trying to get a single thing (The player's rank) instead of the entire object

**Comment by hmes98318** [comment]
> Im just trying to get a single thing (The player's rank) instead of the entire object

try using the following method
```js
async function main() {
    let general = await R6.general(platform, name);
    console.log(`level: ${general.level}`);
}
main();
```
The available parameters for each function are [here](https://github.com/hmes98318/r6s-stats-api#valid-parameters).

**Comment by AidanTheJsDev** [comment]
> try using the following method
> 
> ```js
> async function main() {
>     let { level } = await R6.general(platform, name);
>     console.log(`level: ${level}`);
> }
> main();
> ```

That worked. But is there a way to get player stats from a specific season?

**Comment by AidanTheJsDev** [comment]
> > That worked. But is there a way to get player stats from a specific season?
> 
> No, it doesn't have this feature yet Currently only the current season can be fetch

Thats what im trying to get but the matches is the overall matches that the player has played along with the K/D its the overall K/D out of all the seasons the player has played

**Comment by hmes98318** [comment]
I try to add get player stats from a specific season.
